import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{execFileSync}from'node:child_process';
import{hash,buildCellContext,sourceCellPolygon}from'../../../tools/regiongen/cell-region.mjs';
import{toLocalPoint,fromLocalPoint}from'../../../tools/regiongen/local-source-context.mjs';
import{settlementContext,relativeScale,angularDifference}from'../src/context.mjs';
import{scanNeighbours}from'../src/neighbours.mjs';
const folder='research/game73',read=async p=>JSON.parse(await readFile(p)),worlds={};
for(const stem of['game-11-determinism','atlas-showcase']){const bytes=await readFile(`tests/worldgen/fixtures/${stem}.json`);worlds[stem]={world:JSON.parse(bytes),fp:hash(bytes),bytes,sidecar:await read(`${folder}/inputs/${stem}.geography.json`)}}
const cases=await read(folder+'/examples/cases.json'),contexts={};for(const c of cases.cases)contexts[c.slug]=await read(`${folder}/examples/${c.slug}.context.json`);
test('Exact canonical fixture bytes preserved against published GAME71/72 base',()=>{for(const[stem,w]of Object.entries(worlds)){const baseline=execFileSync('git',['show',`ec6f8b5887826268366a9063f2099b34ae44d297:tests/worldgen/fixtures/${stem}.json`],{maxBuffer:32*1024*1024});assert(w.bytes.equals(baseline));assert.equal(w.fp,cases.cases.find(c=>c.stem===stem).canonicalSha256)}});
for(const c of cases.cases)test(`${c.slug}: exact source identity, deterministic context and correct parent geometry`,()=>{const w=worlds[c.stem],fresh=settlementContext(w.world,w.sidecar,w.fp,c.id),again=settlementContext(w.world,w.sidecar,w.fp,c.id);assert.deepEqual(fresh,again);assert.equal(fresh.id,contexts[c.slug].id);assert.equal(fresh.identity.worldSeed,w.world.seed);assert.equal(fresh.identity.parentCellId,c.cellId);assert.deepEqual(fresh.regional.cellPolygon,sourceCellPolygon(w.world,w.sidecar,c.cellId));const burg=w.world.settlements.find(b=>b?.i===c.id);assert.deepEqual(fresh.position.value,[burg.x,burg.y]);assert.equal(fresh.regional.physicalKm,'UNCALIBRATED')});
test('Rename does not affect immutable context identity or source constraints',()=>{for(const c of cases.cases){const w=worlds[c.stem],copy=structuredClone(w.world);copy.settlements.find(b=>b?.i===c.id).name='TEST RENAMED';const result=settlementContext(copy,w.sidecar,w.fp,c.id);assert.equal(result.id,contexts[c.slug].id);assert.deepEqual(result.identity,contexts[c.slug].identity);assert.deepEqual(result.water,contexts[c.slug].water);assert.deepEqual(result.roadApproaches,contexts[c.slug].roadApproaches)}});
test('Wrong-world sidecar/SHA, absent and hidden burgs cannot substitute a town',()=>{const a=worlds['atlas-showcase'],b=worlds['game-11-determinism'];assert.throws(()=>settlementContext(a.world,b.sidecar,b.fp,68));assert.throws(()=>settlementContext(a.world,a.sidecar,b.fp,68));assert.throws(()=>settlementContext(a.world,a.sidecar,a.fp,999999));const copy=structuredClone(a.world);copy.settlements.find(b=>b?.i===68).hidden=true;assert.throws(()=>settlementContext(copy,a.sidecar,a.fp,68))});
for(const stem of Object.keys(worlds))test(`${stem}: complete scan statistics replay, no invented same-cell pair`,async()=>{const w=worlds[stem],saved=await read(`${folder}/examples/${stem}-neighbours.json`);assert.deepEqual(scanNeighbours(w.world,w.sidecar,w.fp),saved);assert.equal(saved.multiBurgCells.length,0);assert.equal(saved.visibleBurgCount,saved.occupiedCellCount);assert(saved.adjacentPairCount>0);assert(saved.windowsWithNeighbourBurg>0)});
test('Genuine pair: adjacency, exact consecutive source road points and separate ownership',()=>{const p=cases.pair,w=worlds['game-11-determinism'];assert(p.adjacent&&!p.sameCell&&p.aSeesB&&p.bSeesA);for(const road of p.directRoadSegments){const source=w.world.routes.find(r=>r.i===road.routeId);assert.equal(source.group,'roads');assert.deepEqual(source.points.slice(road.sourceSegment,road.sourceSegment+2),road.points);assert.deepEqual(new Set(road.points.map(p=>p[2])),new Set(p.cellIds))}for(const slug of['neighbour-a','neighbour-b']){const c=contexts[slug];assert.equal(c.regional.visibleBurgs.filter(b=>b.ownership==='owned').length,1);assert(c.regional.visibleBurgs.some(b=>p.burgIds.includes(b.source_id)&&b.ownership==='neighbour_in_view'));assert(c.regional.visibleBurgs.every(b=>!b.detailedMapAvailable));assert.equal(c.regional.fringe.fraction_of_longest_cell_extent,.2)}});
test('Local/world projections preserve both real burg coordinates in independent views',()=>{for(const c of[contexts['neighbour-a'],contexts['neighbour-b']])for(const b of c.regional.visibleBurgs){const p=fromLocalPoint(b.local_position,c.regional.window);assert(Math.hypot(p[0]-b.world_position[0],p[1]-b.world_position[1])<1e-5)}});
test('Authoritative overlapping cells, roads, approximate rivers and wet masks agree',async()=>{const r=await read(folder+'/evidence/continuity.json');assert.equal(r.gridSamples,81);assert.equal(r.dryMismatches,0);assert.equal(r.scalarMismatches,0);assert(r.sharedCells.length>=2&&r.sharedCells.every(c=>c.identicalPolygon));for(const kind of['routes','rivers']){assert(r[kind].piecesA>0);assert.equal(r[kind].missing,0);assert(r[kind].maxCoordinateDifference<1e-5)}assert(r.decoration.matchingCentresWithDifferentSourceRadii>0)});
test('Source-backed coast and approach arrows retain exact source IDs and coordinates',()=>{for(const c of cases.cases){const ctx=contexts[c.slug],w=worlds[c.stem];for(const road of ctx.roadApproaches){const original=w.world.routes.find(r=>r.i===road.routeId);assert.equal(original.group,road.group);assert(road.sourceSegment<original.points.length-1);assert.equal(road.kind,'source_derived');assert(road.provenance.includes('not a town gate'))}for(const e of ctx.water.shorelineEdges.value){assert.deepEqual(e.points,e.vertexIds.map(id=>w.sidecar.vertices[id]));assert(w.world.cells.heights[w.world.cells.ids.indexOf(e.wetCellId)]<20)}}});
test('Unknowns remain unknown; population absent cannot produce an invented size',()=>{const c=contexts.albanes;assert.equal(c.water.orientation.kind,'unknown');assert.equal(c.river.orientation.value,null);assert.equal(c.unsupported.gatePositions.value,null);const w=worlds['atlas-showcase'],burg=structuredClone(w.world.settlements.find(b=>b?.i===760));delete burg.population;const scale=relativeScale(burg,131,w.world);assert.equal(scale.population.value,null);assert.equal(scale.aestheticEnvelope.value,null)});
test('Relative classes and source-relative envelopes are bounded hypotheses, never kilometre claims',()=>{assert.equal(contexts.batan.scale.category.value,'village');assert.equal(contexts.albanes.scale.category.value,'capital_or_major_fortified');assert.equal(contexts.thilranlena.scale.category.value,'coastal_port');for(const c of Object.values(contexts)){const v=c.scale.aestheticEnvelope;assert.equal(v.kind,'inferred_visual');assert(v.value.targetCellAreaFraction>=.008&&v.value.targetCellAreaFraction<=.12);assert.equal(v.value.physicalKm,'UNCALIBRATED')}assert(contexts.thilranlena.scale.population.value>contexts.albanes.scale.population.value);assert(contexts.thilranlena.scale.cellPolygonArea.value<contexts.albanes.scale.cellPolygonArea.value)});
test('Actual preserved entrances and coastline show rotation is not automatically a correction',async()=>{const t=await read(folder+'/examples/thilranlena.town-assessment.json');assert(t.waterOrientation.visibleSegments.length>5);assert(t.rotationExperiment.originalWaterDifference<2);assert(t.rotationExperiment.rotatedWaterDifference>10);assert(t.rotationExperiment.rotatedRoadErrors.every((e,i)=>e.deltaDegrees>t.rotationExperiment.originalRoadErrors[i].deltaDegrees));assert(t.entrances.some(e=>e.kind==='harbour'&&e.routes.some(r=>r.kind==='foot')))});
test('Original town art and inherited regional files remain byte-identical',async()=>{for(const slug of['batan','albanes','thilranlena']){const t=await read(`${folder}/examples/${slug}.town-assessment.json`);assert.equal(hash(await readFile(`research/game69/art/${slug}.original.svg`)),t.originalArtSha256);assert.equal(hash(await readFile(`research/game69/art/${slug}.public.svg`)),t.artSha256);assert((await readFile(`${folder}/regions/${slug}.json`)).equals(await readFile(`research/game70/regions/${slug}.json`)))}});
test('Actual raster evidence hashes and source-backed cases are complete',async()=>{const m=await read(folder+'/evidence/visual-manifest.json');assert(m.renderer.startsWith('rsvg-convert'));assert(!m.gameScreenshots);for(const c of m.scaleChart)assert(Math.abs(Math.PI*c.circleRadiusPixels**2/c.cellSidePixels**2-c.proposedAreaFraction)<1e-10);assert(m.renders.length>=19);for(const r of m.renders){assert.equal(hash(await readFile(r.svg)),r.sourceSha256);assert.equal(hash(await readFile(r.png)),r.pngSha256);assert.deepEqual(r.pixels,[1000,1000])}for(const c of cases.cases)assert((await readFile(`${folder}/evidence/${c.slug}-phone.png`)).length>5000)});
test('Research-only scope: all protected production, canonical data, saves and previous research unchanged',()=>{const paths=execFileSync('git',['diff','--name-only','ec6f8b5887826268366a9063f2099b34ae44d297'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);assert(paths.length>0);assert(paths.every(p=>p.startsWith('research/game73/')))});

test('Ordinary town scale reference is an actual source burg, with no invented detailed map',async()=>{const s=await read(folder+'/examples/relative-scale.json'),town=s.cases.find(c=>c.scale.category.value==='town');assert(town);const w=worlds['atlas-showcase'],b=w.world.settlements.find(b=>b?.i===town.identity.burgId);assert(b&&!b.port&&!b.capital&&b.group==='town');assert.equal(town.label,b.name);assert.equal(town.detailedMapAvailable,false);assert.equal(town.buildingCount,null)});
