import {createRequire} from 'node:module';import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
const built=resolve(process.argv[2]??'/tmp/game78-native'),out=resolve(process.argv[3]??'research/game78/evidence/native');mkdirSync(out,{recursive:true});
const core=await import(pathToFileURL(built+'/node_modules/@lexiconlang/core/index.js')),lex=await import(pathToFileURL(built+'/node_modules/@lexiconlang/fantasy/index.js'));
const summary={};function batch(name,n,fn){const rows=[],errors=[];let replay=0;const t=performance.now();for(let k=0;k<n;k++){try{const a=JSON.parse(JSON.stringify(fn(k))),b=JSON.parse(JSON.stringify(fn(k)));if(JSON.stringify(a)===JSON.stringify(b))replay++;rows.push({index:k,output:a});}catch(e){errors.push({index:k,error:String(e)})}}writeFileSync(out+'/'+name+'.json',JSON.stringify(rows,null,2)+'\n');summary[name]={requested:n,completed:rows.length,replay_equal:replay,distinct:new Set(rows.map(r=>JSON.stringify(r.output))).size,errors,milliseconds:performance.now()-t};return rows;}
for(const [name,g] of Object.entries(lex.generators))batch('lexicon-'+name,100,k=>g.generate(core.createContext({seed:'GAME78:native:'+k}).child(name)));
const cultures=['dwarvish','elvish','orcish','halfling','draconic','plantoid','mycanoids','celestial','fey','tiefling'];const language=await import(pathToFileURL(built+'/node_modules/@lexiconlang/language/index.js'));
for(const culture of cultures)batch('lexicon-culture-'+culture,100,k=>language.generateName(lex[culture],'given',core.createContext({seed:'GAME78:culture:'+k})));
const orderRoot=()=>core.createContext({seed:'GAME78:order'});let a=orderRoot(),b=orderRoot();const first=lex.npc.generate(a.child('npc'));lex.questHook.generate(b.child('quest'));const second=lex.npc.generate(b.child('npc'));summary.lexicon_child_order=JSON.stringify(first)===JSON.stringify(second);
a=lex.fantasy.withSeed('order');b=lex.fantasy.withSeed('order');const x=a.npc;b.quest();summary.lexicon_convenience_order=JSON.stringify(x)===JSON.stringify(b.npc);
const names=JSON.parse(readFileSync(out+'/lexicon-fullName.json'));summary.lexicon_native_name_language_disagreement=names.filter(r=>r.output.given.language!==r.output.surname.language).length;
const contextTests=[];for(let k=0;k<100;k++){const inland=core.createContext({seed:'context:'+k,tags:['inland','forest'],data:{port:false,walls:false,culture:'actual-a'}}),port=core.createContext({seed:'context:'+k,tags:['port','desert'],data:{port:true,walls:true,culture:'actual-b'}});const a=lex.npc.generate(inland),b=lex.npc.generate(port);contextTests.push({index:k,equal:JSON.stringify(a)===JSON.stringify(b)});}summary.lexicon_native_npc_ignores_geography=contextTests.filter(x=>x.equal).length;
const require=createRequire(import.meta.url),fcg=require(built+'/fcg/index.js');for(const name of ['NPCs','Storyhooks','Loots','MagicItems','Settlements','Establishments','Names'])batch('fcg-'+name,100,k=>fcg[name].generate({seed:'GAME78:'+k}));
batch('fcg-Storyhooks-controlled-bank',100,k=>fcg.Storyhooks.generate({seed:'GAME78:'+k,storyhookBank:['NPC_ACTS','PC_RELATED','LOCATION_BASED_URBAN','LOCATION_BASED_WILDERNESS'][k%4]}));
// Preserve native failures above. Explicitly conditioned supported magic branches
// are separately measured rather than replacing unsuccessful calls.
for(const school of ['evocation','abjuration','necromancy','transmutation','conjuration','divination','enchantment','illusion'])batch('fcg-magic-'+school,100,k=>fcg.MagicItems.generate({seed:'GAME78:magic:'+k,type:'weapon',schoolOfMagic:school}));
writeFileSync(out+'/metrics.json',JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(Object.fromEntries(Object.entries(summary).map(([k,v])=>[k,typeof v==='object'?{n:v.completed,replay:v.replay_equal,errors:v.errors.length}:v])),null,2));
