import {readFileSync,writeFileSync,readdirSync,mkdirSync,cpSync,existsSync} from 'node:fs';import {join,relative,resolve} from 'node:path';import {createHash} from 'node:crypto';
const built=resolve(process.argv[2]??'/tmp/game78-native'),target=resolve('research/game78/vendor'),rows=[];const hash=b=>createHash('sha256').update(b).digest('hex');
function copy(from,to,repo,pin,upstream){mkdirSync(to,{recursive:true});for(const e of readdirSync(from,{withFileTypes:true})){const f=join(from,e.name),t=join(to,e.name);if(e.isDirectory())copy(f,t,repo,pin,join(upstream,e.name));else if(e.name.endsWith('.js')){const original=readFileSync(f,'utf8');const code=original.replace(/@lexiconlang\/(core|grammar|markov|language|glyphs)/g,(_,p)=>relative(to,join(target,'lexicon',p,'index.js')).replaceAll('\\','/').replace(/^(?!\.)/,'./'));writeFileSync(t,code);rows.push({file:relative(target,t),repository:repo,commit:pin,original_path:join(upstream,e.name.replace(/\.js$/,'.ts')),license:repo.includes('Rant')?'ISC':'MIT',kind:'code',redistributed:true,compiled_sha256:hash(code),modifications:'Node 24 TypeScript transform; relative local ESM imports; upstream source otherwise unchanged'});}}}
for(const p of ['core','grammar','markov','language'])copy(join(built,'node_modules/@lexiconlang',p),join(target,'lexicon',p),'ianlintner/lexiconlang','da0a823e275d9642731bdaed1f3006d2c9bfae74','packages/'+p+'/src');
// Copy only engine-reachable imports. No en-US/Rantionary data, browser, CLI or defaults.
const seen=new Set();function rant(file){if(seen.has(file))return;seen.add(file);const code=readFileSync(join(built,'rant',file),'utf8');for(const m of code.matchAll(/(?:from\s*|import\s*)["'](\.\.?\/[^"']+)["']/g))rant(relative(join(built,'rant'),resolve(join(built,'rant',file,'..'),m[1])));const dest=join(target,'rant',file);mkdirSync(join(dest,'..'),{recursive:true});writeFileSync(dest,code);rows.push({file:'rant/'+file,repository:'robbestad/Rantjs',commit:'c62d5b21b9da9be561c15afdccd5f352cdb91e64',original_path:'src/'+file.replace(/\.js$/,'.ts'),license:'ISC',kind:'code',redistributed:true,compiled_sha256:hash(code),modifications:'Node 24 TypeScript transform and .ts to .js import paths only'});}
rant('engine.js');
for(const [name,source]of [['lexicon','lexiconlang'],['rant','Rantjs']]){cpSync('/tmp/game77-audit/'+source+'/LICENSE',join(target,name,'LICENSE'));writeFileSync(join(target,name,'package.json'),'{"type":"module"}\n');}
for(const row of rows){const repo=row.repository.includes('Rant')?'Rantjs':'lexiconlang';const source='/tmp/game77-audit/'+repo+'/'+row.original_path;if(existsSync(source))row.original_sha256=hash(readFileSync(source));row.required_notice=repo==='Rantjs'?'vendor/rant/LICENSE':'vendor/lexicon/LICENSE';row.copyright=repo==='Rantjs'?'Upstream Rantjs copyright in retained ISC notice':'Copyright (c) 2026 Ian Lintner';}
writeFileSync(join(target,'provenance.json'),JSON.stringify(rows,null,2)+'\n');console.log({files:rows.length,bytes:rows.reduce((n,r)=>n+readFileSync(join(target,r.file)).length,0)});
