class_name ReliefMapLayer
extends MapLayer

## GAME-23: consume provider-neutral relief placement generated by Azgaar.
## Items are already deterministically distributed and bottom-edge ordered.

func _draw() -> void:
	if not model:
		return

	if model.relief.is_empty():
		_draw_fallback()
		return

	for item_value in model.relief:
		if not item_value is Dictionary:
			continue
		var item: Dictionary = item_value
		var kind := str(item.get("kind", "unknown"))
		if kind not in ["mount", "mountSnow", "hill"]:
			continue

		var p := Vector2(float(item.get("x", 0.0)), float(item.get("y", 0.0)))
		var size := float(item.get("size", 6.0))
		# Azgaar stores x/y as the icon box origin. Draw from the visual centre.
		p += Vector2(size * 0.5, size * 0.5)
		var variant := int(item.get("variant", 1))
		_draw_relief_symbol(p, size, kind, variant)

func _draw_relief_symbol(p: Vector2, source_size: float, kind: String, variant: int) -> void:
	var zoom_factor := 0.72 if zoom_band == 0 else (0.9 if zoom_band == 1 else 1.0)
	var size := clampf(source_size * 0.18 * zoom_factor, 2.0, 9.5)
	var jitter := float(posmod(variant * 17, 5) - 2) * 0.08

	if kind == "hill":
		draw_arc(p, size, PI, TAU, 12, Color("#514638", 0.55), 0.9)
		draw_arc(p + Vector2(size * 0.55, 0), size * 0.7, PI, TAU, 10, Color("#665746", 0.42), 0.75)
		return

	var ink := Color("#40372f", 0.78)
	var fill := Color("#8d7b60", 0.22)
	var highlight := Color("#d8c79d", 0.46)
	var left := p + Vector2(-size, size * 0.72)
	var peak := p + Vector2(jitter * size, -size)
	var right := p + Vector2(size, size * 0.72)
	var shape := PackedVector2Array([left, peak, right])
	draw_colored_polygon(shape, fill)
	draw_polyline(shape, ink, 1.1, true)
	draw_line(peak, p + Vector2(size * 0.25, size * 0.15), highlight, 0.8)

	if kind == "mountSnow":
		var snow_left := peak.lerp(left, 0.34)
		var snow_right := peak.lerp(right, 0.34)
		draw_colored_polygon(PackedVector2Array([peak, snow_left, p + Vector2(0, -size * 0.35), snow_right]), Color("#d8d3c0", 0.42))

func _draw_fallback() -> void:
	# Old fixtures have no presentation.relief yet. Keep a restrained fallback
	# until regenerated fixtures are checked in.
	if zoom_band == 0:
		return
	for cell_id in model.points.size():
		if cell_id >= model.heights.size():
			continue
		var height := float(model.heights[cell_id])
		if height < 55.0 or posmod(cell_id * 37, 17) != 0:
			continue
		var p := model.point(cell_id)
		var size := clampf((height - 45.0) / 18.0, 2.0, 5.0)
		_draw_relief_symbol(p, size * 4.0, "mount", 1)
