extends SceneTree
var checks := 0
var failures := 0
func check(ok: bool, why: String) -> void:
 checks += 1
 if not ok:
  failures += 1
  push_error(why)
func _initialize() -> void:
 var base := OS.get_environment("GAME80_TEST_ROOT")
 var library := GameWorldLibrary.new()
 library.library_root = base.path_join("library")
 library.save_root = base.path_join("saves")
 var phase := OS.get_environment("GAME80_PHASE")
 if phase == "create":
  for i in 5:
   var stage := library.create_staging()
   check(stage.ok, "owned staging")
   check(DirAccess.copy_absolute(base.path_join("generated/game80-world-%d/world.json" % i), stage.directory.path_join("world.json")) == OK, "genuine generated bytes copied")
   var result := library.import_generated(stage.directory)
   check(result.ok, str(result.get("error")))
   if not result.ok: continue
   var entry: Dictionary = result.entry
   var profiles := OriginProfiles.new()
   check(profiles.load_world(entry.world), profiles.error)
   for key in profiles.projection.hometowns:
    var row: Dictionary = profiles.projection.hometowns[key]
    check(row.burg_id == int(key) and row.world_id == entry.id, "source identity")
   var first: Dictionary = profiles.projection.hometowns[profiles.projection.hometowns.keys()[0]]
   var store := GamePlaythroughStore.new()
   store.save_root = library.save_root
   var created := store.create_playthrough(entry.world, int(first.state_id), int(first.burg_id), int(first.province_id))
   created.state.origin_profiles = profiles.descriptor.duplicate(true)
   var old := WorldOriginLore.new()
   check(old.load_world(entry.world, entry.world.enrichment_directory), old.error)
   created.state.origin_enrichment = old.descriptor.duplicate(true)
   check(store.save_new(created.state.playthrough_id, created.state, entry.world).ok, "both packages pinned in independent campaign")
   check(store.load_save(created.state.playthrough_id, entry.world).ok, "immediate persistence")
 else:
  var entries := library.discover()
  check(entries.size() == 7, "restart finds presets and five generated worlds")
  var store := GamePlaythroughStore.new()
  store.save_root = library.save_root
  var names := DirAccess.get_files_at(library.save_root)
  check(names.size() == 5, "exactly five independent saves")
  for name in names:
   var raw := WorldOriginLore.read_json(library.save_root.path_join(name))
   var entry: Dictionary = entries.filter(func(e: Dictionary): return e.id == raw.world_ref.id)[0]
   var slot := name.trim_suffix(".json")
   check(store.load_save(slot, entry.world).ok, "independent-process pinned reload")
   var path: String = library.profiles_directory(entry).path_join("public.json")
   var bytes := FileAccess.get_file_as_bytes(path)
   var file := FileAccess.open(path, FileAccess.WRITE)
   file.store_string("{}")
   file.close()
   check(not store.load_save(slot, entry.world).ok, "corrupt profiles refused")
   check(FileAccess.file_exists(library.save_root.path_join(name)), "campaign retained")
   check(not library.ensure_profiles(entry).ok and FileAccess.get_file_as_string(path) == "{}", "corrupt package never silently replaced")
   file = FileAccess.open(path, FileAccess.WRITE)
   file.store_buffer(bytes)
   file.close()
   check(store.load_save(slot, entry.world).ok, "exact restoration")
   var old_save := raw.duplicate(true)
   old_save.erase("origin_profiles")
   check(store._validate(old_save, entry.world).is_empty(), "legacy campaign retains V1")
   check(not library.delete_world(entry).ok, "used world protected with both sidecars")
  var unused := library.create_staging()
  var source := entries[2]
  check(DirAccess.copy_absolute(source.path, unused.directory.path_join("world.json")) == OK, "dedup source")
  var imported := library.import_generated(unused.directory)
  check(imported.ok and imported.deduplicated, "dedup retains exact packages")
  var old_helper := library.helper_root
  library.helper_root = OS.get_environment("GAME80_OLD_HELPER")
  check(not library.helper_status().ok, "incompatible old helper rejected before Node invocation")
  library.helper_root = old_helper
 var f := FileAccess.open("res://docs/implementation/game80/lifecycle-" + phase + ".json", FileAccess.WRITE)
 f.store_string(JSON.stringify({"checks": checks, "failures": failures, "phase": phase}) + "\n")
 f.close()
 print("GAME-80 lifecycle %s: %d checks, %d failures" % [phase, checks, failures])
 quit(1 if failures else 0)
