import {declutter,publicExport,setKnowledge,reload} from './model.mjs';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const roles={inn:'inns',tavern:'inns',shop:'trading',smithy:'mine',guildhall:'capital',chapel:'monastery',manor:'fort',guardhouse:'fort',stable:'village',warehouse:'trading',pier:'canoes',well:'water-sources',mill:'hamlet'};
let model=null,selected=null,view=null,fitWidth=1,requestGeneration=0;
const stage=$('stage'),terrain=$('terrain'),markers=$('markers'),pointerState=new Map();
let touchTap=null;
const svg=(tag,attrs={},text=null)=>{const el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!==null)el.textContent=text;return el};
const points=ring=>ring.map(p=>p.join(',')).join(' ');
const path=polygon=>polygon.map(r=>'M'+r.map(p=>p.join(',')).join('L')+'Z').join('');
const project=p=>[(p[0]-view.x)/view.w*stage.clientWidth,(p[1]-view.y)/view.h*stage.clientHeight];
const label=e=>e.label+(e.knowledge==='unknown'?' · unknown':'');
function filtered(){return model.establishments.filter(e=>{switch($('filter').value){case'hospitality':return ['inn','tavern'].includes(e.type);case'craft':return ['shop','smithy'].includes(e.type);case'landmark':return ['guildhall','chapel','manor','warehouse','pier'].includes(e.type);case'outdoor':return e.locationType==='outdoor';default:return true}})}
function fit(){const b=model.layout.bounds,w=b.max_x-b.min_x,h=b.max_y-b.min_y,r=stage.clientWidth/stage.clientHeight;view={x:(b.min_x+b.max_x)/2,y:(b.min_y+b.max_y)/2,w:Math.max(w,h*r)*1.12,h:Math.max(h,w/r)*1.12};view.x-=view.w/2;view.y-=view.h/2;fitWidth=view.w;render()}
function zoom(factor,at=[stage.clientWidth/2,stage.clientHeight/2]){const nw=Math.max(fitWidth/25,Math.min(fitWidth*2,view.w/factor)),ratio=nw/view.w;view.x+=(at[0]/stage.clientWidth)*view.w*(1-ratio);view.y+=(at[1]/stage.clientHeight)*view.h*(1-ratio);view.w=nw;view.h=nw*stage.clientHeight/stage.clientWidth;render()}
function focus(e,level=6){const w=fitWidth/level;view={x:e.position[0]-w/2,y:e.position[1]-w*stage.clientHeight/stage.clientWidth/2,w,h:w*stage.clientHeight/stage.clientWidth};render()}
function drawTerrain(){
 terrain.replaceChildren();
 for(const ring of model.geometry.water)terrain.append(svg('polygon',{points:points(ring),fill:'#8ca8a4',stroke:'#647e78','stroke-width':.3}));
 for(const ring of model.geometry.fields)terrain.append(svg('polygon',{points:points(ring),fill:'#c2c19a',stroke:'#8e9474','stroke-width':.22,opacity:.68}));
 const styles={ward:{fill:'#e0cfa9',stroke:'#bcae8b','stroke-width':.14,opacity:.3},green:{fill:'#aeb790',stroke:'none',opacity:.7},field:{fill:'#bcbc90',stroke:'#92926d','stroke-width':.4,opacity:.7},street:{fill:'none',stroke:'#eee2c8','stroke-width':model.layout.units==='metres'?3:.75,'stroke-linecap':'round'},wall:{fill:'none',stroke:'#625947','stroke-width':1.4},tower:{fill:'#82785e',stroke:'#514b3c','stroke-width':.35},pier:{fill:'#9c8160',stroke:'#514635','stroke-width':.5}};
 for(const f of model.geometry.features){const g=f.geometry,style=styles[f.layer];if(!style)continue;
  if(g.type==='Polygon')terrain.append(svg('path',{d:path(g.coordinates),...style,'fill-rule':'evenodd'}));
  else if(g.type==='LineString')terrain.append(svg('polyline',{points:points(g.coordinates),...style}));
  else if(g.type==='MultiLineString')for(const line of g.coordinates)terrain.append(svg('polyline',{points:points(line),...style}));
 }
 const stroke=model.layout.units==='metres'?.42:.14;
 for(const b of model.buildings)terrain.append(svg('path',{d:path(b.polygon),fill:'#ae9170',stroke:'#685944','stroke-width':stroke,'fill-rule':'evenodd'}));
 terrain.append(svg('g',{id:'selection-roof'}));
}
function select(e,{center=false}={}){selected=e;inspect();if(center)focus(e);else render();renderIndex()}
function inspect(){const panel=$('inspection');panel.replaceChildren();const intro=document.createElement('p');intro.className='eyebrow';intro.textContent='PREMISES / INSPECTION';panel.append(intro);
 const title=document.createElement('h2');title.textContent=selected?selected.label:'Choose a place';panel.append(title);
 if(!selected){const p=document.createElement('p');p.textContent='Select a marker or a place in the index. Ordinary roofs have no invented establishment.';panel.append(p);return}
 const e=selected,tags=document.createElement('div');tags.className='tags';for(const text of [e.locationType==='outdoor'?'Outdoor feature':'Existing building',e.knowledge]){const s=document.createElement('span');s.className='tag'+(e.knowledge==='unknown'?' warn':'');s.textContent=text;tags.append(s)}panel.append(tags);
 const dl=document.createElement('dl');const fields=[['Function',e.function],['Name','Unnamed; facility label only'],['Settlement',model.settlement.name],['District',e.district],['Building',e.buildingId||'None — outdoor POI'],['Source ID',e.provenance.providerBuildingId||e.provenance.providerPoiId],['Evidence',e.provenance.evidence],['Provenance','Settlemaker '+e.provenance.providerRevision.slice(0,12)+' · provider-generated'],['Availability','Unknown; no gameplay service inferred']];
 for(const[key,value]of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;dl.append(dt,dd)}panel.append(dl);
 const actions=document.createElement('div');actions.className='inspection-actions';for(const[name,action]of [['Premises view',()=>focus(e,12)],['District view',()=>focus(e,4)]]){const b=document.createElement('button');b.textContent=name;b.onclick=action;actions.append(b)}
 if($('developer').checked){const b=document.createElement('button');b.textContent=e.knowledge==='unknown'?'Mark discovered (demo)':'Hide place (demo)';b.onclick=()=>{model=setKnowledge(model,e.id,e.knowledge==='unknown'?'discovered':'unknown');selected=model.establishments.find(f=>f.id===e.id);inspect();renderIndex();render()};actions.append(b)}panel.append(actions);
 const note=document.createElement('p');note.className='inspection-note';note.textContent='Geometry is original; knowledge state is a hypothetical research example. No owner, inventory, quest or opening hours are invented.';panel.append(note);
}
function renderIndex(){const list=$('place-index');list.replaceChildren();const all=filtered().sort((a,b)=>a.type.localeCompare(b.type)||a.id.localeCompare(b.id));$('index-count').textContent=all.length+' places';for(const e of all){const b=document.createElement('button');b.className='place-row'+(selected?.id===e.id?' active':'')+(e.knowledge==='unknown'?' unknown':'');b.dataset.id=e.id;b.dataset.type=e.type;b.setAttribute('aria-label',`${label(e)}, ${e.district}, ${e.locationType}`);const img=document.createElement('img');img.src=`assets/${roles[e.type]||'unidentified'}.svg`;img.alt='';const text=document.createElement('span'),name=document.createElement('span'),small=document.createElement('small');name.className='place-label';name.textContent=label(e);small.textContent=e.district+' · '+e.locationType;text.append(name,small);b.append(img,text);b.onclick=()=>select(e,{center:true});list.append(b)}}
function render(){if(!model||!view)return;terrain.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);terrain.setAttribute('preserveAspectRatio','none');markers.setAttribute('viewBox',`0 0 ${stage.clientWidth} ${stage.clientHeight}`);markers.replaceChildren();
 const magnification=fitWidth/view.w,showLabels=magnification>=2.5;const candidates=filtered().filter(e=>{const p=project(e.position);return p[0]>18&&p[1]>18&&p[0]<stage.clientWidth-22&&p[1]<stage.clientHeight-22});
 const wantsLabel=e=>(showLabels||selected?.id===e.id||['guildhall','chapel','warehouse','pier'].includes(e.type)) && project(e.position)[0]+22+label(e).length*7.5<stage.clientWidth-5;
 const drawn=declutter(candidates,project,{size:28,labels:wantsLabel,selectedId:selected?.id,labelText:label});
 for(const{item:e}of drawn){const[x,y]=project(e.position),g=svg('g',{transform:`translate(${x} ${y})`,class:'marker '+e.locationType+(e.knowledge==='unknown'?' unknown':'')+(selected?.id===e.id?' selected':''),tabindex:0,role:'button','aria-label':label(e),'data-id':e.id,'data-type':e.type});g.append(svg('circle',{r:14,class:'badge'}));g.append(svg('image',{href:`assets/${roles[e.type]||'unidentified'}.svg`,x:-10,y:-10,width:20,height:20}));
  if(wantsLabel(e))g.append(svg('text',{x:19,y:4,class:'marker-label'},label(e)));
  g.addEventListener('pointerdown',event=>{if(event.pointerType!=='touch')event.stopPropagation()});g.addEventListener('click',()=>select(e));g.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();select(e)}});g.addEventListener('pointerenter',()=>{const t=$('tooltip');t.textContent=label(e)+' · '+e.locationType;t.style.left=Math.min(x+16,stage.clientWidth-180)+'px';t.style.top=Math.max(5,y-33)+'px';t.hidden=false});g.addEventListener('pointerleave',()=>$('tooltip').hidden=true);markers.append(g);
 }
 const overlay=document.getElementById('selection-roof');overlay?.replaceChildren();if(selected?.buildingId){const b=model.buildings.find(b=>b.id===selected.buildingId);overlay.append(svg('path',{d:path(b.polygon),fill:'#d5a25f',stroke:'#923e28','stroke-width':view.w/stage.clientWidth*2,'fill-opacity':.62}))}
 $('view-level').textContent=magnification<2?'Full settlement':magnification<8?'District / neighbourhood':'Individual premises';$('density').textContent=`${drawn.length} markers in view · ${filtered().length} indexed`;
 window.game67State={audience:model.audience,slug:$('settlement').value,selectedId:selected?.id||null,establishmentIds:model.establishments.map(e=>e.id),markers:drawn.map(d=>d.item.id),view:{...view}};
}
async function load(){const generation=++requestGeneration;model=null;selected=null;window.game67State=null;terrain.replaceChildren();markers.replaceChildren();$('place-index').replaceChildren();$('inspection').replaceChildren();$('town-name').textContent='Loading…';$('summary').textContent='';pointerState.clear();$('tooltip').hidden=true;
 const slug=$('settlement').value,developer=$('developer').checked;const response=await fetch(`samples/${slug}.${developer?'developer':'public'}.json`);if(!response.ok)throw Error('Could not load sample');const loaded=reload(await response.text());if(generation!==requestGeneration)return;
 if(loaded.audience!==(developer?'developer':'public'))throw Error('Audience mismatch');model=loaded;
 $('mode').className='mode'+(developer?' developer':'');$('mode').textContent=developer?'DEVELOPER INSPECTION · includes unknown facilities · research scenario':'PUBLIC · discovered facilities only · research knowledge scenario';$('town-name').textContent=model.settlement.name;$('summary').textContent=`${model.buildings.length} original roofs · ${model.establishments.length} ${developer?'source-backed':'known'} facilities · burg ${model.settlement.burgId}`;drawTerrain();renderIndex();inspect();fit();
}
const safelyLoad=()=>load().catch(error=>{$('town-name').textContent='Sample load failed';$('summary').textContent=error.message});
$('settlement').onchange=safelyLoad;$('developer').onchange=safelyLoad;$('filter').onchange=()=>{if(selected&&!filtered().some(e=>e.id===selected.id)){selected=null;inspect()}renderIndex();render()};$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.6);$('zoom-out').onclick=()=>zoom(1/1.6);
$('export').onclick=()=>{const payload=publicExport(model),url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${$('settlement').value}.public.snapshot.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
stage.addEventListener('wheel',e=>{if(!model)return;e.preventDefault();const b=stage.getBoundingClientRect();zoom(e.deltaY<0?1.2:1/1.2,[e.clientX-b.left,e.clientY-b.top])},{passive:false});
stage.addEventListener('pointerdown',e=>{if(!model||e.target.closest('.map-tools'))return;pointerState.set(e.pointerId,[e.clientX,e.clientY]);if(e.pointerType==='touch'){touchTap=pointerState.size===1?{id:e.target.closest('.marker')?.getAttribute('data-id'),x:e.clientX,y:e.clientY}:null}stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!pointerState.has(e.pointerId)||!model)return;const old=pointerState.get(e.pointerId),next=[e.clientX,e.clientY];if(touchTap&&Math.hypot(e.clientX-touchTap.x,e.clientY-touchTap.y)>8)touchTap=null;if(pointerState.size===2){const other=[...pointerState.entries()].find(([id])=>id!==e.pointerId)[1],before=Math.hypot(old[0]-other[0],old[1]-other[1]),after=Math.hypot(next[0]-other[0],next[1]-other[1]),b=stage.getBoundingClientRect();if(before>1&&after>1)zoom(after/before,[(next[0]+other[0])/2-b.left,(next[1]+other[1])/2-b.top])}else{view.x-=(next[0]-old[0])/stage.clientWidth*view.w;view.y-=(next[1]-old[1])/stage.clientHeight*view.h;render()}pointerState.set(e.pointerId,next)});
for(const event of ['pointerup','pointercancel'])stage.addEventListener(event,e=>{if(event==='pointerup'&&touchTap?.id&&e.pointerType==='touch'){const item=model.establishments.find(f=>f.id===touchTap.id);if(item)select(item)}touchTap=null;pointerState.delete(e.pointerId)});
stage.addEventListener('keydown',e=>{if(!model)return;const move={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(move){e.preventDefault();view.x+=move[0]*view.w*.08;view.y+=move[1]*view.h*.08;render()}else if(e.key.toLowerCase()==='f')fit();else if(e.key==='+')zoom(1.6);else if(e.key==='-')zoom(1/1.6)});
new ResizeObserver(()=>{if(!model||!view)return;view.h=view.w*stage.clientHeight/stage.clientWidth;render()}).observe(stage);
await safelyLoad();
