import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {resolve, dirname, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {loadWorld, context, eligible} from '../src/context.mjs';
import {loadPack, canonical, writeImmutable, verify, sha} from '../src/core.mjs';
import {generate, envelope} from '../src/generator.mjs';
import {render, renderingArtifact} from '../src/text.mjs';
import {originPayload} from '../src/visibility.mjs';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const fixture = process.argv[2] ?? resolve(root, 'tests/worldgen/fixtures/game-11-determinism.json');
const output = resolve(process.argv[3] ?? resolve(root, 'research/game77/evidence'));
const world = loadWorld(fixture), pack = loadPack(resolve(root, 'research/game77/packs/trhgd-original-v2.json'));
const marker = world.source.markers.find(m => m && m.type === 'ruins' && !m.hidden && !m.removed);
const burg = world.record('settlements', 771) ?? world.source.settlements.find(eligible);
if (!marker || !eligible(burg)) throw Error('Required real public ruin and eligible hometown unavailable');
const townContext = context(world, 'settlements', burg.i), siteContext = context(world, 'markers', marker.i);
const records = [generate('site',siteContext,pack),generate('origin',townContext,pack),generate('character',townContext,pack,{playthrough_id:'research-demo-001',instance:'starter:1'}),generate('mundane-item',townContext,pack),generate('rare-item',townContext,pack)];
const worldRecords = records.filter(r=>r.scope==='world');
const data = envelope(world.base,pack,worldRecords); verify(data,world.base);
const characterData = envelope(world.base,pack,records.filter(r=>r.scope!=='world'),{scope:'playthrough:research-demo-001'});
mkdirSync(output,{recursive:true});
const sidecar = resolve(output,'enrichment/v1',pack.digest,data.enrichment_sha+'.json');writeImmutable(sidecar,data);
writeFileSync(resolve(output,'examples.json'),JSON.stringify({world_enrichment:data,playthrough_enrichment:characterData},null,2)+'\n');
writeImmutable(resolve(output,'playthrough/research-demo-001/enrichment/v1',pack.digest,characterData.enrichment_sha+'.json'),characterData);
writeFileSync(resolve(output,'rendering.json'),JSON.stringify(renderingArtifact(data),null,2)+'\n');
writeFileSync(resolve(output,'playthrough-rendering.json'),JSON.stringify(renderingArtifact(characterData),null,2)+'\n');
const publicOrigins = {schema_version:1,entries:worldRecords.filter(r=>r.type==='origin').map(r=>originPayload(data,r.source.id))};
writeFileSync(resolve(output,'public-origins.json'),JSON.stringify(publicOrigins,null,2)+'\n');
const escape = s => String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const sections = records.map(r=>`<section><h2>${escape(r.type)}</h2><p>Source: ${escape(r.context.display_name)} · ${escape(r.source.kind)}:${r.source.id} · cell ${r.source.cell_id}</p><h3>Source context — canonical facts / unknowns</h3><pre>${escape(JSON.stringify({culture:r.context.culture,religion:r.context.religion,biome:r.context.biome,roads:r.context.road_ids,trails:r.context.trail_ids,sea_routes:r.context.sea_route_ids,river:r.context.river_id,coast:r.context.coast},null,2))}</pre><h3>Structured TRHGD facts</h3><pre>${escape(JSON.stringify(r.facts,null,2))}</pre><h3>Public prose</h3><p>${escape(render(r))}</p><h3>Rumours — developer truth labels</h3><pre>${escape(JSON.stringify(r.rumours,null,2))}</pre><h3 class="secret">Developer-only hidden/private facts</h3><pre>${escape(JSON.stringify(r.secret,null,2))}</pre></section>`).join('\n');
writeFileSync(resolve(output,'review.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>GAME-77 developer review</title><style>body{background:#151310;color:#d5c29b;font:17px Georgia;max-width:900px;margin:24px auto;padding:12px}section{border-top:1px solid #776449;padding:14px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px monospace}.secret{color:#d9998f}</style><h1>GAME-77 — developer review</h1><p>Genuine source anchors; generated fiction is not Azgaar history. This document deliberately includes secrets and is never loaded by the player UI.</p><p>World ${escape(world.base.seed)}; canonical SHA ${world.base.sha256}. Enrichment SHA ${data.enrichment_sha}.</p>${sections}`);
writeFileSync(resolve(output,'REVIEW.md'),'# GAME-77 review examples\n\nDeveloper-only review; rumours carry truth labels here, never in player projections.\n\n'+records.map(r=>`## ${r.type}\n\nSource: ${r.context.display_name}, ${r.source.kind}:${r.source.id}, cell ${r.source.cell_id}.\n\n${render(r)}\n\nStructured facts and hidden/private fields: [examples.json](examples.json).\n`).join('\n'));
if (sha(readFileSync(fixture))!==world.base.sha256) throw Error('Source mutation');
console.log(JSON.stringify({world_id:world.base.id,burg_id:burg.i,marker_id:marker.i,enrichment_sha:data.enrichment_sha,sidecar:relative(output,sidecar),records:records.length,base_unchanged:true},null,2));
