"""Regenerate the research results page from validated, complete batch artifacts."""
import gzip
import hashlib
import json
from pathlib import Path
from collections import Counter
from run import cases, aggregate
from combat import Battle

ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).parent/'results'
DOC=ROOT/'docs/research/game86/SIMULATION-RESULTS.md'


def main():
    manifest=json.loads((OUT/'manifest.json').read_text())
    for name,digest in manifest.items():
        assert hashlib.sha256((OUT/name).read_bytes()).hexdigest()==digest,name
    rows=[json.loads(line) for line in gzip.decompress((OUT/'battles.jsonl.gz').read_bytes()).splitlines()]
    groups={g:[] for g,_,_ in cases()}
    for row in rows:groups[row['group']].append(row)
    for g,n,_ in cases():
        assert len(groups[g])==n and [r['seed'] for r in groups[g]]==list(range(n)),g
    summaries=[aggregate(g,groups[g]) for g,_,_ in cases()]
    assert summaries==json.loads((OUT/'summary.json').read_text())
    by={r['group']:r for r in summaries}
    invocations=[json.loads(p.read_text()) for p in sorted((OUT/'timings').glob('*.json'))]
    timing=next(t for t in invocations if t['resumed_selected_groups']==0)
    lines=['# GAME-86 simulation results','',
        '**Completed: 209 groups, 19,456 seeded battles. No sampling reduction. Research-only toy model; no production combat.**','',
        'Generated by `python3 research/game86/report.py`; the generator verifies artifact hashes, each original group/seed count, and summaries reconstructed from raw rows. See [METHOD](METHOD.md), [recommendation](RECOMMENDATION.md), [runtime investigation](RUNTIME.md) and [candidate comparison](MODEL-COMPARISON.md).','',
        f'Raw archive SHA-256: `{manifest["battles.jsonl.gz"]}`. Raw rows include every timeout, result, metric and final state hash. Group checkpoints retain per-group wall time; `timings/` preserves completed invocation timing separately from deterministic artifact hashes.','',
        f'This recorded invocation took **{timing["seconds"]:.3f} seconds** with **{timing["workers"]} workers**; summed group wall time is {timing["group_seconds_sum"]:.3f}s. These are machine-dependent observations, not a speed guarantee.','',
        '## Interpretation before selection','',
        '- Win rates measure these fixed kits under one public-state greedy policy. They do not rank the final classes, price utility, or establish human enjoyment. The simulations omit saving throws, real stealth, directional cover, escape, build progression and most spell choices.',
        '- A permits one ordinary attack with movement; B permits two full attacks while stationary; C permits three with penalties. They are complete economy packages. C\'s shorter rounds and fewer walking-only activations do not prove shorter wall-clock play or better choices.',
        '- Most party rows favour the fighter/rogue/mage side, but the opposite side has a controller whose policy spends actions on unreliable-value Slow. That composition/controller confound precludes attributing party advantage to rogue or mage strength.',
        '- Slow vs none below is a counterexample to treating more seeded runs as AI validation: using Slow correlates with *more opponent wins* in this policy. Stun denies actual activations, but its net effect also includes foregone attacks and altered paths. No per-spell damage-equivalent claim is justified.',
        '- Spatial mirroring uses different odd/even seeds, not a same-seed side/initiative crossover. Keyed attack ordinals also cease to represent the same event once policies diverge. Paired comparisons reduce sampling noise without eliminating these biases.',
        '- Wilson intervals cover seeded sampling only. Geometry has 32 seeds per cell; scale6 has 32 per configuration, so fine distinctions are particularly uncertain. Duplicate baselines in different families are reproducibility checks, not independent replication.','',
        '## Core matchups','',
        'Left is the first named class (party: fighter/rogue/mage vs fighter/archer/controller). Each model/terrain cell has n=128. Rates include timeouts as non-wins. A-contact is the observed melee activation median; censored actors are listed separately. A-exposure is attempts per melee actor including censored actors. The full per-model metrics and Wilson intervals are in `summary.csv`.','',
        '| Matchup | Terrain | A left win | B left win | C left win | A contact / censored | A exposure | A/B/C timeouts |',
        '|---|---|---:|---:|---:|---:|---:|---|']
    for match in ('fighter_archer','fighter_rogue','rogue_archer','mage_fighter','mage_monk','monk_archer','party'):
        for terrain in ('open','moderate','dense','objective'):
            a,b,c=[by[f'core/{m}/{match}/{terrain}'] for m in 'ABC']
            lines.append(f'| {match} | {terrain} | {a["left_win_rate"]:.1%} | {b["left_win_rate"]:.1%} | {c["left_win_rate"]:.1%} | {a["median_contact_activation_observed"]} / {a["contact_censored_n"]} | {a["precontact_attempts_per_melee_including_censored"]} | {a["timeouts"]}/{b["timeouts"]}/{c["timeouts"]} |')
    def table(title,prefix):
        lines.extend(['',f'## {title}','','| Group | n | Left wins (95% CI) | Timeout | Mean rounds | Walking-only | Denied / slowed activations per battle | Casts / interrupts |','|---|---:|---|---:|---:|---:|---:|---:|'])
        for r in summaries:
            if r['group'].startswith(prefix):
                lines.append(f'| {r["group"]} | {r["n"]} | {r["left_win_rate"]:.1%} ({r["win_ci_low"]:.1%}–{r["win_ci_high"]:.1%}) | {r["timeouts"]} | {r["mean_rounds"]} | {r["walking_only_fraction"]:.1%} | {r["mean_denied_turns"]} / {r["mean_slowed_turns"]} | {r["casts"]} / {r["interrupts"]} |')
    for title,prefix in [('Approach-tool ablations','ablation/'),('Initiative scheduling','initiative/'),('Control choices','control/'),('Lethality sensitivity','lethality/'),('Rogue contexts','rogue/'),('Six units per side','scale6/')]:table(title,prefix)
    lines.extend(['','## Paired control differences','',
                  'These are **left-side** win differences; the controller belongs to the right side. SE is descriptive across shared seeds, not a causal model or an adjustment for policy error.','',
                  '| Comparison | n | Difference | Descriptive SE | Discordant seeds |','|---|---:|---:|---:|---:|'])
    for r in json.loads((OUT/'paired.json').read_text()):lines.append(f'| {r["paired"]} | {r["n"]} | {r["mean"]:.4f} | {r["descriptive_se"]:.4f} | {r["discordant_seeds"]} |')
    lines.extend(['','## Geometry: all 78 factorial cells retained','',
                  '32 seeds per row; fighter vs archer under A on open terrain. Invalid gap/size combinations were already excluded in the pushed design. See every cell below; changing ranges and movement jointly changes encounter geometry, not just class strength.','',
                  '| Size / gap / bow / fighter move | Fighter wins | Timeout | Contact observed / censored | Pre-contact attempts |','|---|---:|---:|---:|---:|'])
    for r in summaries:
        if r['group'].startswith('geometry/'):
            lines.append(f'| {r["group"][9:]} | {r["left_win_rate"]:.1%} | {r["timeouts"]} | {r["mean_contact_activation_observed"]} / {r["contact_censored_n"]} | {r["precontact_attempts_per_melee_including_censored"]} |')
    diagnostic=json.loads((OUT/'diagnostics.json').read_text())
    lines.extend(['','## Counterexamples and exact arithmetic','','| Lane diagnostic | Contact turn | Shots before contact |','|---|---:|---:|'])
    for name,r in diagnostic['lane'].items():lines.append(f'| {name} | {r["contact_turn"]} | {r["shots_before_contact"]} |')
    lines.extend(['',
        'The unbounded equal-speed lane preserves an endless firing/retreat cycle without approach tools. A finite board can hide it. Dash sacrifices attacks to gain ground; charge requires a straight clear lane. These tools do not guarantee safe contact against superior movement, blockers or coordinated ranged units.',
        '',f'The illusion observation diagnostic changes route length from {diagnostic["illusion"]["detour_steps"]} to {diagnostic["illusion"]["direct_steps"]} after one observer spends a main action investigating. Another observer still believes the wall. A decoy attack spends its action before learning the target is false. This proves a narrow information/command boundary, not class balance or damage prevented.',
        '', 'Exact d20 enumeration gives +7 vs AC15 a 65% hit chance and 5.4 expected damage at base8/+4 critical. Two independent misses occur with probability 12.25%. A 34HP fighter therefore takes roughly 6.30 such attacks to lose 34HP by expectation; this ratio is not the expected stopping time, and real focus-fire/reactions change it.',
        '', 'One automatic full-activation stun removes one-third of a three-member team\'s activations, versus one-sixth with six members. A 1.5× CT activation rate combined with 1.5× movement yields 2.25× traversal per reference time. These are arithmetic warnings, not tested CT or campaign simulations.',
        '', '## Expensive groups and repeated baselines','', '| Group | Battles | Seconds |','|---|---:|---:|'])
    for r in sorted(timing['groups'],key=lambda r:r['seconds'],reverse=True)[:10]:lines.append(f'| {r["group"]} | {r["battles"]} | {r["seconds"]:.4f} |')
    lines.extend(['',
        'No experiment required reduced sampling. `initiative/individual` and `control/slow` are identical 256-seed configurations. `lethality/*/1.0` repeats core moderate-party baselines, and several rogue rows repeat core configurations. Preserve these scheduled rows, but do not count them twice as independent evidence. Larger parties and long maneuvering fights cost more; the recorded group timing makes that cost visible.',
        '', '## Decision and remaining evidence gates','',
        '**Recommend A: movement + one main action, one shared reaction, bounded approach tools, and telegraphed limited magic.** This is a readability and interaction choice supported by viable approach behavior, not an optimization for a target win rate. B rewards stationary double attacks; C makes movement less costly but adds attack-penalty bookkeeping and still produced dense-terrain stalls.',
        '', 'Before class tuning: add same-seed side/initiative crossover, at least a conservative and a coordinating policy, Guard/protect/escape decisions, and per-turn regret inspection. Before shipping: human tests on 3v3 and selected 6v6 layouts, directional cover, actual observation-restricted illusions/stealth, saving throws, resources across encounters, and save/replay of the same engine. These are additional acceptance gates, not omitted scheduled experiments.'])
    lines.extend(['', 'See the [actual seeded 3v3 command walkthrough](WALKTHROUGH.md), including a telegraphed burst that hits nobody.'])
    DOC.write_text('\n'.join(lines)+'\n')
    write_walkthrough()
    print('Verified and wrote',DOC)


def write_walkthrough():
    trace=json.loads((OUT/'walkthrough.json').read_text())
    battle=Battle(seed=trace['seed'],left=tuple(trace['left']),right=tuple(trace['right']),terrain=trace['terrain'])
    units={u.id:u for u in battle.units}
    lines=['# Actual seeded 3v3 walkthrough','',
           'Research diagnostic, not a Godot gameplay capture. This is the original fixed seed1, modelA, moderate12×12 matchup, not a selected showcase win. The raw ordered events and command replay proof are in `research/game86/results/walkthrough.json`.','',
           '![Research board: initial walls, cover and units](figures/walkthrough-board.svg)','',
           'The board shows the initial state; coordinates increase right/down. Dark gray tiles are walls, tan tiles are cover, blue units are team0 and red units team1.','',
           '**Initial order:** '+ ' → '.join(f"{identity} {units[identity].kind}" for identity in trace['initiative'])+'.','',
           '| Round | Actor | Actual command / resolution |','|---|---|---|']
    for event in trace['events']:
        if event['round']>2:continue
        actor=event['actor'];kind=event['type']
        if kind=='command':
            c=event['command']
            if c['action']=='end':continue
            description=c['action']
            if c['path']:description+=' via '+str(c['path'])
            if c['target']:description+=' target '+c['target']
            if c['tile']:description+=' locked tile '+str(c['tile'])
        elif kind=='hit':description=f"roll {event['roll']}, penalty {event['penalty']}, damage {event['damage']}; {event['target']} HP now {event['hp']}"
        elif kind=='burst':description=f"burst resolves at {event['tile']}; victims {event['victims']}"
        else:description=str(event)
        lines.append(f"| {event['round']} | {actor} {units[actor].kind} | {description} |")
    lines.extend(['','## Remaining rounds','', '| Round | Attack attempts | Hit damage | Burst damage events | Defeated actors |','|---|---:|---:|---:|---|'])
    for round_number in range(3,trace['result']['rounds']+1):
        events=[e for e in trace['events'] if e['round']==round_number]
        hits=[e for e in events if e['type']=='hit']
        lines.append(f"| {round_number} | {len(hits)} | {sum(e['damage'] for e in hits)} | {sum(e['type']=='burst' for e in events)} | {', '.join(e['target'] for e in hits if e['hp']==0) or 'none'} |")
    lines.extend(['',
        'The mage spends a Focus on a tile occupied by clustered enemies. They move before resolution; the burst hits nobody. This is visible counterplay and also potentially poor target selection. Without a paired counterfactual it is not valid to credit the cast with a particular amount of prevented damage.',
        '', 'The fighter charges into the opposing fighter while the rogue reaches an allied-threat position and deals10 damage. That illustrates the toy support condition, not geometric flanking. On round2 the slowed mage spends main on Disengage and moves two tiles; it does not attack for free. The controller spends both Focus on Slow while the opposing team kills its fighter. This trace makes the policy opportunity-cost concern concrete.',
        '', f"Team{trace['result']['outcome']} wins in round{trace['result']['rounds']}. Replaying the same commands through a fresh Battle matches every result field; final state SHA-256 is `{trace['command_replay_sha256']}`. Manual control is represented here only by replaying the same command interface; no production manual controller has been implemented."])
    (DOC.parent/'WALKTHROUGH.md').write_text('\n'.join(lines)+'\n')
    parts=['<svg xmlns="http://www.w3.org/2000/svg" width="490" height="470" viewBox="0 0 490 470">',
           '<rect width="490" height="470" fill="#faf7ef"/>',
           '<text x="20" y="22" font-family="sans-serif" font-size="16">GAME-86 research board — seed 1, initial state</text>']
    for x in range(12):
        parts.append(f'<text x="{55+x*32}" y="46" font-family="monospace" font-size="11">{x}</text>')
        parts.append(f'<text x="26" y="{73+x*32}" font-family="monospace" font-size="11">{x}</text>')
        for y in range(12):
            color='#404754' if (x,y) in battle.board.walls else '#dfcca7' if (x,y) in battle.board.cover else '#f5f1e8'
            parts.append(f'<rect x="{48+x*32}" y="{54+y*32}" width="32" height="32" fill="{color}" stroke="#aaa" stroke-width="0.5"/>')
    for u in battle.units:
        x,y=u.pos;color='#2468a2' if u.team==0 else '#a43a38'
        parts.append(f'<circle cx="{64+x*32}" cy="{70+y*32}" r="14" fill="{color}"/>')
        parts.append(f'<text x="{64+x*32}" y="{74+y*32}" text-anchor="middle" font-family="monospace" font-size="11" fill="white">{u.id}</text>')
    parts.append('<text x="20" y="458" font-family="sans-serif" font-size="12">Blue: fighter / rogue / mage. Red: fighter / archer / controller.</text></svg>')
    (DOC.parent/'figures').mkdir(exist_ok=True)
    (DOC.parent/'figures/walkthrough-board.svg').write_text('\n'.join(parts)+'\n')

if __name__=='__main__':main()
